# Site settings ...
uri: domain.com
url: https://domain.com
name: drzq
title: 杂录
email: drzq14@gmail.com
author: drzq
keywords: "Your, Keyword, Here"
description: "The joy's always been in the discovery."
social_username: username

# Build settings ...
sass:
  style: compressed
markdown: kramdown
paginate: 5
permalink: /post/:title
paginate_path: "/page/:num/"
exclude:
  - README.md

# Plugins ...
plugins:
  - jekyll-paginate
  - jemoji
